# Setup
title: a blog
tagline: by elif sema balcıoğlu
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options
nav:
  - title: Archive
    url: /archive

  - title: Notes
    url: /notes
  
  - title: Books
    url: /books

  - title: About
    url: /about

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Elif Sema Balcıoğlu
  url: https://twitter.com/mdo
  email: elifsemabalcioglu@gmail.com

# Custom vars
version: 3.0.0
